# Generated by Django 5.2.6 on 2025-09-26 16:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0024_alter_user_last_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 25, 22, 0, 44, 751929), null=True),
        ),
        migrations.CreateModel(
            name='AndroidDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(unique=True)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_time', models.TimeField(default=datetime.time(9, 0))),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('daily_reminders_enabled', models.BooleanField(default=True)),
                ('community_notifications_enabled', models.BooleanField(default=True)),
                ('achievement_notifications_enabled', models.BooleanField(default=True)),
                ('last_sent_date', models.DateField(blank=True, null=True)),
                ('last_sent_time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='android_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
