# Generated by Django 5.2.6 on 2025-09-26 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0025_alter_user_last_checkin_androiddevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 25, 22, 17, 33, 585622), null=True),
        ),
    ]
