# Generated by Django 5.2.6 on 2025-09-26 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0026_alter_user_last_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='androiddevice',
            name='android_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='androiddevice',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='androiddevice',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='androiddevice',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='androiddevice',
            name='screen_density',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='androiddevice',
            name='system_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='androiddevice',
            name='token_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='androiddevice',
            name='token_refresh_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='androiddevice',
            name='total_notifications_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 25, 22, 37, 1, 963962), null=True),
        ),
        migrations.AddIndex(
            model_name='androiddevice',
            index=models.Index(fields=['user', 'is_active'], name='ecotrack_an_user_id_9e11f6_idx'),
        ),
        migrations.AddIndex(
            model_name='androiddevice',
            index=models.Index(fields=['fcm_token'], name='ecotrack_an_fcm_tok_075350_idx'),
        ),
        migrations.AddIndex(
            model_name='androiddevice',
            index=models.Index(fields=['notification_time', 'timezone'], name='ecotrack_an_notific_8acedc_idx'),
        ),
        migrations.AddIndex(
            model_name='androiddevice',
            index=models.Index(fields=['last_sent_date', 'last_sent_time'], name='ecotrack_an_last_se_782359_idx'),
        ),
    ]
