# Generated by Django 5.2.6 on 2025-09-27 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0027_androiddevice_android_version_androiddevice_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 26, 15, 36, 21, 187473), null=True),
        ),
    ]
