# Generated by Django 5.2.6 on 2025-09-27 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0029_alter_user_last_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 26, 15, 37, 2, 241325), null=True),
        ),
    ]
