# Generated by Django 5.2.6 on 2025-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0030_alter_user_last_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='survey_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
