# Generated by Django 5.2.6 on 2025-11-20 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrack', '0031_user_survey_skipped_alter_user_last_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 11, 19, 15, 58, 23, 789399), null=True),
        ),
    ]
